### ISSUE TITLE
Failed to activate the pg-dev package

### ISSUE THREAD

**Issue by ghost** [arianbessonart/pg-dev#12]
1. Open Atom with pg-dev enabled

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [pg-dev](https://github.com/arianbessonart/pg-dev) package 0.7.1

### Stack Trace

Failed to activate the pg-dev package

```
At atom.workspace.getActivePaneItem(...).getRootScopeDescriptor is not a function

TypeError: atom.workspace.getActivePaneItem(...).getRootScopeDescriptor is not a function
    at /packages/pg-dev/lib/go-to-provider.js:34:111
    at Workspace.observeActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:802:13)
    at Object.getFunctionDefinition (/packages/pg-dev/lib/go-to-provider.js:33:37)
    at Object.activate (/packages/pg-dev/lib/pg-dev.js:22:18)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:603:52)
    at /usr/share/atom/resources/app/src/atom-environment.js:846:34
```

### Commands

```
     -0:46.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
hyperclick 0.1.1 
intentions 1.1.2 
language-pgsql 0.2.3 
less-postcss-autocompile 1.2.3 
linter 2.2.0 
linter-ui-default 1.6.2 
pg-dev 0.7.1 
```

**Comment by arianbessonart** [comment]
Hello @sjstoelting a new version was realease today. 
Please update and check again.

Thank you.
